/*
 * This file was autogenerated by TinyMPC on Tue Jun  2 02:21:35 2026
 */

#pragma once

#include <tinympc/types.hpp>

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;
void tiny_init_generated_data(void);

#ifdef __cplusplus
}
#endif
