/*
 * This file was autogenerated by TinyMPC on Tue Jun  2 02:14:17 2026
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
